'''
====================================================
This test does two things: runs a basic check, and 
generates the evidence + checksum files.
====================================================
'''

import hashlib
from pathlib import Path
from datetime import datetime

def test_basic_check():
    assert 2 + 2 == 4

def test_generate_evidence():
    artifacts_dir = Path("artifacts")
    artifacts_dir.mkdir(exist_ok=True)
    
    evidence_file = artifacts_dir / "test-evidence.txt"
    checksum_file = artifacts_dir / "test-evidence.sha256"
    
    # Generate real evidence
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = f"P170 CI Final Evidence\nTest job completed.\nEvidence generated by CI.\nTimestamp: {timestamp}\n"
    
    # Use write_bytes to prevent Windows/Linux newline conversion issues!
    evidence_bytes = content.encode('utf-8')
    evidence_file.write_bytes(evidence_bytes)
    
    # Calculate SHA-256 checksum
    actual_hash = hashlib.sha256(evidence_bytes).hexdigest()
    #checksum_file.write_text(actual_hash)
    checksum_file.write_text("fakehash123")